### ISSUE TITLE
【Nostrオフ会】考えとかないといけないこと

### ISSUE THREAD

**Issue by kojira** [ShinoharaTa/off_meeting#1]
- [x] おおまかなスケジュールの策定(レンタル開始終了時間、買い出し、料理、ボードゲーム、後片付けなどなど)
- [x] 買い出しお手伝いしてくれる人の募集
- [x] 具体的に何やるかを決める(料理とボードゲームだけ？)
- [x] 料理は誰が何を作るか(買い出しに影響あり)
- [x] ボードゲーム何するか(持ち込める人に確認、あるいは買うなど)
- [x] 精算方法の詳細
- [x] BGMなんか流す？
- [x] 二次会どこに行くか(参加できる人で多数決なり)

これらのうち、手間がかかりそうなやつはチケット化、すぐ決められるものはREADMEに書く

**Comment by ShinoharaTa** [comment]
Child issues

#2 
#3 
#4
#5 
#6

**Comment by ShinoharaTa** [comment]
@kojira 
チケット分解しました
