### ISSUE TITLE
【Nostrオフ会】買い出し、お手伝いの参加者募集

### ISSUE THREAD

**Issue by ShinoharaTa** [ShinoharaTa/off_meeting#2]
買い出し、お手伝いのスタッフ募集

各1名

- 参加者・ゲストの入室管理、案内（1名
- 買い出し（4名
- 買い出し中にセットアップ（2名

**Comment by kojira** [comment]
何作るかにもよるけど
買い出しは4人くらい居たほうがいいかも

**Comment by ShinoharaTa** [comment]
4名２変更

**Comment by ShinoharaTa** [comment]
変更があった場合はこちらのコメントを修正します

１．買い出し

こじらさん、青ぎさん、みりめいさん、しおんさん

２．受付
へいほうさん、ななみんさん
（交代で）

３．会場準備

しのさん、ぽーまんさん、かまくらさん
