### ISSUE TITLE
【Nostrオフ会】イベント中の企画

### ISSUE THREAD

**Issue by ShinoharaTa** [ShinoharaTa/off_meeting#3]
イベント中にやりたいことを募集しています

予定

- 手羽先あげよう！
- ボードゲームやろう！
- スマブラ・マリカ等Switchのゲームできるよ
- LTやりたい人いる？
- プログラムそこで書いたりしたいとか！

その他。コメントに記載してください

**Comment by kojira** [comment]
たこ焼きする？

**Comment by ShinoharaTa** [comment]
たこ焼き器のレンタルあります。やりましょか

**Comment by kojira** [comment]
たこ焼きは反対する人も少ないだろうからやってしまおう。
たこ焼き器2個は欲しいところ

**Comment by ShinoharaTa** [comment]
一つはラボのを借りますか

**Comment by kojira** [comment]
ラボの持っていこう

ハイブリッド開催の企画も考えないとなー

**Comment by ShinoharaTa** [comment]
行きがけにラボのを回収お願いします！

**Comment by darashi** [comment]
村ラジオ機材用意しておきます！

**Comment by ShinoharaTa** [comment]
@darashi ありがとうございます
#9 に別のタスク立てました
