### ISSUE TITLE
【Nostrオフ会】料理の予定

### ISSUE THREAD

**Issue by ShinoharaTa** [ShinoharaTa/off_meeting#4]
- 手羽先をあげる？
- それ以外のものを作る？（手巻き寿司とか
- ホットケーキ焼き
- お好み焼き
- たこ焼き

その他は買い出しでサイドメニューも考えます

**Comment by kojira** [comment]
これもリストを載せてNostrのNIP-69でアンケート？
(実装クライアントあったっけ)

**Comment by ShinoharaTa** [comment]
実装クライアントあったっけ・・・？
こちらにコメントで募集しますかね？

**Comment by kojira** [comment]
誰かが実装してくれる可能性が微レ存()

**Comment by ShinoharaTa** [comment]
【手作りメニュー】

手羽先
たこやき
もしかしたら餃子？
