### ISSUE TITLE
【Nostrオフ会】ボードゲーム何にしよう

### ISSUE THREAD

**Issue by ShinoharaTa** [ShinoharaTa/off_meeting#5]
備え付け

- 人生ゲーム
- ジェンガ
- 黒ひげ危機一発
- カタン
- 人狼
- ブロックス
- UNO
- はぁって言うゲーム
- トランプ

やりたいゲーム持ち込みたいゲーム募集

**Comment by kojira** [comment]
このリストを載せて持ち込める人をnostrで募集しよう

**Comment by kojira** [comment]
人が多そうな時間に

**Comment by penpenpng** [comment]
4人前後用のボードゲームならいくつか持ってます (引っ越しダンボールのどこかにあるのでリストできないですけど…)

**Comment by ShinoharaTa** [comment]
@penpenpng 
助かります！！
当日に向けてボードゲームやりたい希望者のどれやりたい！など取りまとめなどお願いできますか・・・？

**Comment by penpenpng** [comment]
@ShinoharaTa 
事前に discord でアンケート取るのでもいいですけど、ぼくの持っているのはどれも物理的に小さいんで適当に持ってってその場のノリでもいい気がしています

**Comment by ShinoharaTa** [comment]
承知しました！
では準備おねがいします
その場で決まる感じにしましょう

**Comment by kisato** [comment]
だいぶ日が経ってますけど、「テストプレイなんてなんてしてないよ」というSNEのカードゲームをポチったので持っていきます。
こちらもその場の状況見合いで使えそうなら使う感じで。プレイヤー数は2〜10人らしいです。

**Comment by ShinoharaTa** [comment]
@kisato よろしくお願いします！
