### ISSUE TITLE
【Nostrオフ会】二次会の場所を検討しましょう

### ISSUE THREAD

**Issue by ShinoharaTa** [ShinoharaTa/off_meeting#6]
候補

- 回転寿司（くら寿司）
- カラオケ
- 居酒屋

行きたいお店があればコメントください

**Comment by kojira** [comment]
くら寿司は人数的に流石にキツそうだなあ
居酒屋かなあ
その後は自由にカラオケ行くなりなんなり

**Comment by ShinoharaTa** [comment]
池袋のスシローだったかな、以前15人ぐらいで予約したことあり。
流石にテーブルは分かれました

**Comment by kojira** [comment]
くら寿司で長居するの迷惑かなあって

**Comment by ShinoharaTa** [comment]
居酒屋検討中
どこかおすすめあれば・・・

**Comment by akanetojo** [comment]
池袋も居酒屋もあまり馴染みがないのでおすすめもわからないんですが
とりあえず検索してみました。
仮として4月8日18:00、12名を検索条件にしています

https://www.hotpepper.jp/SA11/Y050/XA9B/G001_G002_G003_G004_G005_G006_G007_G008/20230408_1830_rpn12/sit8/

**Comment by akanetojo** [comment]
ちなみにくら寿司アプリを持っていたのでこちらも検索してみました。
10名以上でも予約できるみたいでした

![A5B21ECF-14DA-45FF-B2A5-FF1826CACABB](https://user-images.githubusercontent.com/124443181/229288770-e5030584-74a0-4be3-b466-44dc09cef7c9.jpeg)

**Comment by ShinoharaTa** [comment]
@akanetojo 
ありがとうございます！！
いけるのですね・・・（困惑

とりあえず電話してみます

**Comment by ShinoharaTa** [comment]
池袋の風
（３年ほど前に行った経験あり）

https://goo.gl/maps/551gSFBxs5JEBRFX6

**Comment by ShinoharaTa** [comment]
ちばチャンバル

https://goo.gl/maps/SnXpNLWAJBY3PnBx8

**Comment by ShinoharaTa** [comment]
ちばチャン
唐揚げとか串焼きとか

https://goo.gl/maps/SnXpNLWAJBY3PnBx8
