### ISSUE TITLE
【Nostrオフ会】名札をつくろう

### ISSUE THREAD

**Issue by ShinoharaTa** [ShinoharaTa/off_meeting#7]
参加者の名札をつくります
当日、コンビニプリントで印刷してその場で切って名札に入れる作業があります

**Comment by kojira** [comment]
マジックでその場で紙に書いたらええんちゃう？
名札入れはどっかに在庫あったかもしれん。

**Comment by ShinoharaTa** [comment]
来た順に書いてもらいますかー

**Comment by kojira** [comment]
そうしよう。
印刷は費用対効果悪い。
できる人は自分で紙印刷か名刺を入れるとか

**Comment by ShinoharaTa** [comment]
注文済み。

**Comment by ShinoharaTa** [comment]
メモ
用紙とペンを買う
