### ISSUE TITLE
【Nostrオフ会】村ラジオの準備

### ISSUE THREAD

**Issue by ShinoharaTa** [ShinoharaTa/off_meeting#9]
当日の村ラジオを流す

**Comment by ShinoharaTa** [comment]
僕はBluetooth スピーカー持ち込みます
※BGM用なので、ラジオ用は別にあったほうがいいかも

**Comment by darashi** [comment]
専用のノートPCとBluetoothスピーカーをセッタップしておきました。当日持ち込めれば大丈夫なはずです！

**Comment by ShinoharaTa** [comment]
ありがとうございます！！
:aza:
